api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
#    formats:
#        json: ['application/json']
    patch_formats:
        #json: ['application/json']
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
